<a href="https://colab.research.google.com/github/Aeagon07/Pytourch/blob/main/Dataset_and_Dataloader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from sklearn.datasets import make_classification
import torch

In [4]:
#  Creating synthestic data
x, y = make_classification(
    n_samples=10,       # Number of samples
    n_features=2,       # Number of feature
    n_informative=2,    # Number of informative feature
    n_redundant=0,      # Number of redundant feature
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [5]:
x

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [6]:
x.shape

(10, 2)

In [7]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [8]:
y.shape

(10,)

In [9]:
# convert it into the tensors
X = torch.tensor(x, dtype=torch.float32)
Y = torch.tensor(y, dtype=torch.float32)

In [10]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [15]:
Y

tensor([1., 0., 0., 0., 0., 1., 1., 1., 1., 0.])

In [16]:
# Now
from torch.utils.data import Dataset, DataLoader

In [14]:
class custDataSet(Dataset):
  def __init__(self, features, labels):
    super().__init__()

    self.feature = features
    self.label = labels

  def __len__(self):
    return self.feature.shape[0]

  def __getitem__(self, index):
    return self.feature[index], self.label[index]

In [17]:
dataset = custDataSet(X, Y)

In [18]:
len(dataset)

10

In [19]:
dataset[0]

(tensor([ 1.0683, -0.9701]), tensor(1.))

In [20]:
#  Now we craete the object of the dataloader class
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)
# this is dataloader is itterable so you can loop through

In [21]:
for batch_features, batch_label in dataloader:
  print(batch_features)
  print(batch_label)
  print("-" * 50)

tensor([[-1.9629, -0.9923],
        [-0.7206, -0.9606]])
tensor([0., 0.])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [-1.1402, -0.8388]])
tensor([0., 0.])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [-0.9382, -0.5430]])
tensor([1., 1.])
--------------------------------------------------
tensor([[1.8997, 0.8344],
        [1.7774, 1.5116]])
tensor([1., 1.])
--------------------------------------------------
tensor([[ 1.0683, -0.9701],
        [-0.5872, -1.9717]])
tensor([1., 0.])
--------------------------------------------------
