<a href="https://colab.research.google.com/github/Aeagon07/Pytourch/blob/main/PyT_Training_Pipline_Improved_Version.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [5]:
df.shape

(569, 33)

In [6]:
# You don't need the column id and Unnamed: 32
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [7]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

## Train Test Split

In [8]:
# We divided into 80-20 split, 80 -> Train and 20 -> Test
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

## Scaling (Basic Preprocessing)

In [9]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [10]:
x_train

array([[-1.4423397 , -1.15130825, -1.45154742, ..., -1.50623883,
         0.14381048, -0.29155119],
       [-0.8661975 , -0.51543186, -0.84781722, ..., -0.28280028,
        -0.19052843,  1.8621648 ],
       [-0.73195077, -2.01161159, -0.7472631 , ..., -1.00541955,
         0.77604377, -0.49714327],
       ...,
       [-0.2928521 ,  0.75164535, -0.20840653, ..., -0.01989275,
         1.94543767,  1.35096286],
       [-0.39074034, -1.39209967, -0.40018919, ..., -0.44888677,
        -0.53279006, -0.04206242],
       [ 0.03157749,  0.75398313,  0.06527909, ...,  0.33546909,
        -0.32046108,  0.0123917 ]])

In [11]:
y_train

307    B
507    B
313    B
227    B
360    B
      ..
441    M
250    M
208    B
312    B
536    M
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [12]:
encode = LabelEncoder()
y_train = encode.fit_transform(y_train)
y_test = encode.fit_transform(y_test)

In [13]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,

## NumPy arrays to PyTorch Tensors

In [14]:
x_train_tesnsor = torch.from_numpy(x_train)
x_test_tesnsor = torch.from_numpy(x_test)
y_train_tesnsor = torch.from_numpy(y_train)
y_test_tesnsor = torch.from_numpy(y_test)

In [15]:
x_train_tesnsor.shape

torch.Size([455, 30])

In [16]:
y_train_tesnsor.shape

torch.Size([455])

## DataSet and DataLoader

In [17]:
#  The Improvement using the dataset and dataloader
from torch.utils.data import Dataset, DataLoader

class custDataset(Dataset):

  def __init__(self, features, labels):
    self.feature = features
    self.label = labels

  def __len__(self):

    return len(self.feature)

  def __getitem__(self, idx):
    return self.feature[idx], self.label[idx]

In [18]:
train_dataset = custDataset(x_train_tesnsor, y_train_tesnsor)
test_dataset = custDataset(x_test_tesnsor, y_test_tesnsor)

In [25]:
train_dataset[10]

(tensor([ 0.1211,  0.7844,  0.1715, -0.0057, -0.8138,  0.5390,  0.1610, -0.3002,
         -1.2887, -0.1642, -0.6531, -0.1939, -0.3277, -0.4540, -0.9095,  1.1437,
          1.0539,  0.6937, -0.5148,  0.2438, -0.1686,  0.2633, -0.0457, -0.2639,
         -1.2842,  0.4219,  0.4361, -0.0515, -1.0177, -0.1804],
        dtype=torch.float64),
 tensor(0))

In [26]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

## Define the Model (Creation of Model)

In [19]:
class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, x):
    out = self.linear(x)
    out = self.sigmoid(out)

    return out


### Important Parameters

In [20]:
learning_rate = 0.1
epochs = 25

In [21]:
# Loss Function using the nn module
loss_function = nn.BCELoss()
# Simple that is only change you have to do

### Training Pipline

In [32]:
import torch.optim as optim

# create the model
model = MySimpleNN(x_train_tesnsor.shape[1])

# define optimizer
optimizer = optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(epochs):

  for batch_feature, batch_label in train_loader:

    # Forward Pass
    y_pred = model(batch_feature.float())

    # Loss Calculation
    loss = loss_function(y_pred, batch_label.view(-1, 1).float())
    # What happen first was y_pred having the shape [455] but the y_train_tensor having shap of [455, 1] so you just reshape or use the view

    # Clear Gradients
    optimizer.zero_grad()

    # Backward Pass
    # You have to calculate the derviate
    loss.backward()

    # Parameters Updation
    optimizer.step()

    # Print Loss inn epoch
    print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.6744555830955505
Epoch: 1, Loss: 0.472581684589386
Epoch: 1, Loss: 0.46890389919281006
Epoch: 1, Loss: 0.32200074195861816
Epoch: 1, Loss: 0.3587481677532196
Epoch: 1, Loss: 0.27527135610580444
Epoch: 1, Loss: 0.2609190344810486
Epoch: 1, Loss: 0.21738201379776
Epoch: 1, Loss: 0.27561256289482117
Epoch: 1, Loss: 0.18703049421310425
Epoch: 1, Loss: 0.27871954441070557
Epoch: 1, Loss: 0.19169290363788605
Epoch: 1, Loss: 0.16376321017742157
Epoch: 1, Loss: 0.20382069051265717
Epoch: 1, Loss: 0.1256401538848877
Epoch: 2, Loss: 0.1806558221578598
Epoch: 2, Loss: 0.23232975602149963
Epoch: 2, Loss: 0.14715225994586945
Epoch: 2, Loss: 0.12894730269908905
Epoch: 2, Loss: 0.2151196449995041
Epoch: 2, Loss: 0.1606573760509491
Epoch: 2, Loss: 0.11971918493509293
Epoch: 2, Loss: 0.13370376825332642
Epoch: 2, Loss: 0.16662433743476868
Epoch: 2, Loss: 0.14024925231933594
Epoch: 2, Loss: 0.26020103693008423
Epoch: 2, Loss: 0.1063309758901596
Epoch: 2, Loss: 0.11708422750234604
Epoch

In [23]:
model.linear.weight

Parameter containing:
tensor([[ 0.3683,  0.1450,  0.3180,  0.3306,  0.1088,  0.0135,  0.2324,  0.1414,
          0.1179,  0.0679,  0.1054, -0.1315,  0.1885,  0.2591,  0.0513, -0.0800,
         -0.1244,  0.2095,  0.0837, -0.0583,  0.2549,  0.2519,  0.3056,  0.3278,
          0.0755,  0.2626,  0.2291,  0.0653,  0.0017,  0.1504]],
       requires_grad=True)

### Evaluation

In [33]:
# model evaluation -> Basically you send the test data to do every thing again
with torch.no_grad():

  for batch_featrure, batch_labe in test_loader:

    y_pred = model.forward(batch_feature.float())
    y_pred = (y_pred > 0.9).float()
    # When you increased your threshold then it increases the accurancy

    accurancy = (y_pred == batch_label).float().mean()

  print(f'Accurancy: {accurancy.item()}')

Accurancy: 0.5306122303009033
