<a href="https://colab.research.google.com/github/Aeagon07/Pytourch/blob/main/PyT_Training_Pipline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd
import torch

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [6]:
df.shape

(569, 33)

In [9]:
# You don't need the column id and Unnamed: 32
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [10]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

## Train Test Split

In [11]:
# We divided into 80-20 split, 80 -> Train and 20 -> Test
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

## Scaling (Basic Preprocessing)

In [12]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [13]:
x_train

array([[ 1.44321324,  1.6895044 ,  1.56362234, ...,  1.08092978,
        -0.99962398,  0.43610583],
       [-1.12497236, -0.40301694, -1.11025952, ..., -0.91978563,
         0.25305138,  0.2057653 ],
       [-0.87736702, -1.02408492, -0.87831135, ..., -0.73600352,
         0.50055578, -0.65091991],
       ...,
       [-0.58081644, -1.38000465, -0.5790773 , ..., -0.63639642,
        -0.20828337, -0.21690389],
       [ 0.14760391,  0.9728875 ,  0.09545307, ...,  0.32958982,
        -0.72012921, -0.90679079],
       [-1.16815933,  0.49275418, -1.19091898, ..., -1.38680109,
        -0.93564325, -0.21179782]])

In [14]:
y_train

83     M
222    B
381    B
103    B
285    B
      ..
1      M
209    B
529    B
385    M
425    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [15]:
encode = LabelEncoder()
y_train = encode.fit_transform(y_train)
y_test = encode.fit_transform(y_test)

In [16]:
y_train

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,

## NumPy arrays to PyTorch Tensors

In [17]:
x_train_tesnsor = torch.from_numpy(x_train)
x_test_tesnsor = torch.from_numpy(x_test)
y_train_tesnsor = torch.from_numpy(y_train)
y_test_tesnsor = torch.from_numpy(y_test)

In [18]:
x_train_tesnsor.shape

torch.Size([455, 30])

In [20]:
y_train_tesnsor.shape

torch.Size([455])

## Define the Model (Creation of Model)

In [43]:
class MySimpleNN():

  def __init__(self, x):
    self.weight = torch.rand(x.shape[1], 1, dtype=torch.float64, requires_grad=True) # Initializing weights with the random values in range of feature here it is 30
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True) # Initializing bias from 0

  def forward_pass(self, x):
    z = torch.matmul(x, self.weight) + self.bias
    return torch.sigmoid(z)

  def loss_function(self, y_pred, y):
    # Clamp prediction to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    # Calculate the loss
    loss = -(y_train_tesnsor * torch.log(y_pred) + (1 - y_train_tesnsor) * torch.log(1-y_pred)).mean()
    return loss






### Important Parameters

In [44]:
learning_rate = 0.1
epochs = 25

### Training Pipline

In [45]:
# create the model
model = MySimpleNN(x_train_tesnsor)
model.weight # It is matrix of the 30*1

tensor([[0.2280],
        [0.6260],
        [0.9889],
        [0.8965],
        [0.9226],
        [0.5093],
        [0.9978],
        [0.2440],
        [0.9270],
        [0.4568],
        [0.8073],
        [0.4112],
        [0.0190],
        [0.5808],
        [0.2852],
        [0.7310],
        [0.0699],
        [0.8293],
        [0.0675],
        [0.8330],
        [0.5902],
        [0.9207],
        [0.3113],
        [0.0020],
        [0.3601],
        [0.1645],
        [0.4653],
        [0.4179],
        [0.3435],
        [0.3236]], dtype=torch.float64, requires_grad=True)

In [46]:
model.bias # It is scaler conatining 1 single itme as 0

tensor([0.], dtype=torch.float64, requires_grad=True)

In [42]:
# Now, Train the model

#  These following steps we do this in loop mean how many epoch you define that many time
for epoch in range(epochs):
  # Forward Pass
  y_pred = model.forward_pass(x_train_tesnsor)

  # Loss Calculation
  loss = model.loss_function(y_pred, y_train_tesnsor)

  # Backward Pass
  # You have to calculate the derviate
  loss.backward()

  # Parameters Updation
  with torch.no_grad():
    # If you want to calculate these you don't need to track the grad
    model.weight -= learning_rate * model.weight.grad
    model.bias -= learning_rate * model.bias.grad

  # Zero Gradients -> You don't want to accumulate the gradients that's why
  model.weight.grad.zero_()
  model.bias.grad.zero_()

  # Print Loss inn epoch
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")


Epoch: 1, Loss: 3.4565945177417574
Epoch: 2, Loss: 3.4565945177417574
Epoch: 3, Loss: 3.4565945177417574
Epoch: 4, Loss: 3.4565945177417574
Epoch: 5, Loss: 3.4565945177417574
Epoch: 6, Loss: 3.4565945177417574
Epoch: 7, Loss: 3.4565945177417574
Epoch: 8, Loss: 3.4565945177417574
Epoch: 9, Loss: 3.4565945177417574
Epoch: 10, Loss: 3.4565945177417574
Epoch: 11, Loss: 3.4565945177417574
Epoch: 12, Loss: 3.4565945177417574
Epoch: 13, Loss: 3.4565945177417574
Epoch: 14, Loss: 3.4565945177417574
Epoch: 15, Loss: 3.4565945177417574
Epoch: 16, Loss: 3.4565945177417574
Epoch: 17, Loss: 3.4565945177417574
Epoch: 18, Loss: 3.4565945177417574
Epoch: 19, Loss: 3.4565945177417574
Epoch: 20, Loss: 3.4565945177417574
Epoch: 21, Loss: 3.4565945177417574
Epoch: 22, Loss: 3.4565945177417574
Epoch: 23, Loss: 3.4565945177417574
Epoch: 24, Loss: 3.4565945177417574
Epoch: 25, Loss: 3.4565945177417574


In [47]:
model.weight

tensor([[0.2280],
        [0.6260],
        [0.9889],
        [0.8965],
        [0.9226],
        [0.5093],
        [0.9978],
        [0.2440],
        [0.9270],
        [0.4568],
        [0.8073],
        [0.4112],
        [0.0190],
        [0.5808],
        [0.2852],
        [0.7310],
        [0.0699],
        [0.8293],
        [0.0675],
        [0.8330],
        [0.5902],
        [0.9207],
        [0.3113],
        [0.0020],
        [0.3601],
        [0.1645],
        [0.4653],
        [0.4179],
        [0.3435],
        [0.3236]], dtype=torch.float64, requires_grad=True)

### Evaluation

In [56]:
# model evaluation -> Basically you send the test data to do every thing again
with torch.no_grad():
  y_pred = model.forward_pass(x_test_tesnsor)
  y_pred = (y_pred > 0.9).float()
  # When you increased your threshold then it increases the accurancy

  accurancy = (y_pred == y_test_tesnsor).float().mean()

print(f'Accurancy: {accurancy.item()}')

Accurancy: 0.5220067501068115
