<a href="https://colab.research.google.com/github/Aeagon07/Pytourch/blob/main/PyTorch_NN_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
#  Create the model class
import torch
import torch.nn as nn

# Create the class
class Model(nn.Module):
  # You must inherite the our model class from the nn module class

  def __init__(self, num_features):
    super().__init__() # here you invoke the nn module class

    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

# In Pytorch the functions are already defines so if you change the name of the function then it not run properly

  def forward(self, x):
    out = self.linear(x) # z = wx + b
    out = self.sigmoid(out) # doing Activation sigmod(z)

    return out


In [12]:
# create dataset
features = torch.rand(10, 5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward_pass(features) -> you can do this way too but in pT recommanded you to don't do this way instead of use below approach
model(features)

# What we doing is create the model object and simply call it as the funtion

tensor([[0.6986],
        [0.6473],
        [0.6387],
        [0.7013],
        [0.6278],
        [0.7028],
        [0.6430],
        [0.6338],
        [0.6792],
        [0.6377]], grad_fn=<SigmoidBackward0>)

In [13]:
model.linear.weight

Parameter containing:
tensor([[0.2527, 0.0035, 0.0583, 0.3576, 0.1451]], requires_grad=True)

In [14]:
model.linear.bias

Parameter containing:
tensor([0.3328], requires_grad=True)

In [15]:
# If you want to visulalize the whole network as you done in keras and all then
# you have the in build libray
!pip install torchinfo

In [16]:
from torchinfo import summary

summary(model, input_size=(10, 5))

# Why 6 -> 5 parameters and 1 bias

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Improved Neutral Network

In [18]:
 #  Create the model class
import torch
import torch.nn as nn

# Create the class
class Model(nn.Module):

  def __init__(self, num_features):
    super().__init__()

    self.linear1 = nn.Linear(num_features, 3) # how many outcome you will take when first inputs are going
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1) # It takes 3 input and give the 1 output
    self.sigmoid = nn.Sigmoid()


  def forward(self, x):
    out = self.linear1(x) # z = wx + b
    out = self.relu(out) # doing Activation sigmod(z)

    out = self.linear2(out)
    out = self.sigmoid(out)

    return out


In [19]:
# create dataset
features = torch.rand(10, 5)

# create model
model = Model(features.shape[1])

# call model for forward pass
model(features)


tensor([[0.6230],
        [0.6024],
        [0.5952],
        [0.6014],
        [0.5976],
        [0.5855],
        [0.6173],
        [0.5982],
        [0.5995],
        [0.5832]], grad_fn=<SigmoidBackward0>)

In [20]:
model.linear1.weight # Must give -> 5*3 = 15

Parameter containing:
tensor([[ 0.4315,  0.1666, -0.2162, -0.1590,  0.2988],
        [ 0.1809,  0.1525, -0.4004, -0.0823,  0.0284],
        [-0.1239,  0.1863, -0.4046, -0.1123,  0.3767]], requires_grad=True)

In [21]:
model.linear2.weight # Must Give -> 3*1 = 3

Parameter containing:
tensor([[ 0.4722, -0.3509,  0.0270]], requires_grad=True)

In [22]:
model.linear1.bias # Must Give -> 3 bias

Parameter containing:
tensor([-0.1012,  0.3076,  0.0333], requires_grad=True)

In [23]:
model.linear2.bias# Must Give -> 1 bias

Parameter containing:
tensor([0.4195], requires_grad=True)

In [24]:
!pip install torchinfo

In [27]:
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### Use the Sequential Container intsead of repeating and going from each layer

In [28]:
 #  We only write the changes here
import torch
import torch.nn as nn

# Create the class
class Model(nn.Module):

  def __init__(self, num_features):
    super().__init__()

    self.network = nn.Sequential(
      nn.Linear(num_features, 3) ,
      nn.ReLU(),
      nn.Linear(3, 1),
      nn.Sigmoid()
    )


  def forward(self, x):
    out = self.network(x)

    return out


# **Optim Module**

In [ ]:
# define optizer !

optimizer = torch.optim.SGD(model.parameters(), lr=25) # Try to execute it after model creation

# model.parameters is basically the iterator over all the trainable parameters(weights and biases) => It means if you want to access the all the
# parameters in your defined model they you have to use the model.parameters()

# Then calll
optimizer.step()

# And Take care of the gradient zeros is done by single line of the code
optimizer.zero_grad()
# -> This pass is better to run before the backward() pass