<a href="https://colab.research.google.com/github/Aeagon07/Pytourch/blob/main/Tensors_In_Pytourch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.8.0+cu126


In [3]:
if torch.cuda.is_available():
  print("GPU is Available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not Available!")

GPU is not Available!


## **Creating Tensors**

In [6]:
# using empty
a = torch.empty(2, 3)
print(a)

In [7]:
type(a)

torch.Tensor

In [8]:
# Using Zeros
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
# Using Ones
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
# Using Rand
torch.rand(2, 3)

tensor([[0.9877, 0.3366, 0.9557],
        [0.7316, 0.7326, 0.3795]])

In [15]:
#  Other Ways

# Arrange
print(f"Tesor Using Arrange: {torch.arange(0, 10)} \n")

# Linespace
print(f"Tesor Using Linspace: {torch.linspace(0, 10, 10)} \n")

# eye
print(f"Tesor Using EYE: {torch.eye(3)} \n")

Tesor Using Arrange: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 

Tesor Using Linspace: tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000]) 

Tesor Using EYE: tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]) 



## **Tensor Shape**

In [18]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
x.shape

torch.Size([2, 3])